/**
 * @file epos.h
 * @brief Header for Maxon Motor EPOS serial port communication driver.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

enum {
	SUCCESS = 0,
	FAIL = -1
};

enum {
	READ_OBJECT_OPCODE = 0x10,
	WRITE_OBJECT_OPCODE = 0x11
} epos_opcode;

enum {
  EPOS_SOFTWARE_VERSION_INDEX = 0x2003,
  EPOS_CONTROL_WORD_INDEX=0x6040,
  EPOS_STATUS_WORD_INDEX = 0x6041,
  EPOS_MODES_OPERATION_INDEX=0x6060,
  EPOS_VELOCITY_MODE_SP_INDEX=0x206B,
  EPOS_POSITION_MODE_SP_INDEX=0x2062,
  EPOS_TARGET_VELOCITY_INDEX=0x60FF,
  EPOS_TARGET_POSITION_INDEX=0x607A,
  EPOS_VELOCITY_ACTUAL_VALUE_INDEX = 0x2028,
  EPOS_POSITION_ACTUAL_VALUE_INDEX= 0x6064,
  EPOS_DEFINE_POSITION_INDEX = 0x2081
} epos_obj_index_t;

enum {
  EPOS_FAULT_RESET_CMD=0x0080,
  EPOS_SHUTDOWN_CMD=0x0006,
  EPOS_SWITCH_ON_CMD=0x0007,
  EPOS_ENABLE_OPERATION_CMD=0x000F,
  EPOS_HALT_CMD=0x010F,
  EPOS_GOTO_POSITION_REL_CMD=0x007F,
  EPOS_GOTO_POSITION_ABS_CMD=0x003F,
  EPOS_GOTO_VELOCITY_CMD=0x000F
} epos_commands_t;

typedef enum {
  EPOS_HOMING_MODE=0x06,
  EPOS_PROFILE_VELOCITY_MODE=0x03,
  EPOS_PROFILE_POSITION_MODE=0x01,
  EPOS_POSITION_MODE=0xFF,
  EPOS_VELOCITY_MODE=0xFE,
  EPOS_CURRENT_MODE=0xFD,
  EPOS_DIAGNOSTIC_MODE=0xFC,
  EPOS_MASTER_ENCODER_MODE=0xFB,
  EPOS_STEP_DIRECTION_MODE=0xFA
} epos_mode_t;